[2025-05-16T10:46:33.313+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-16T10:46:33.336+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_stock_news_and_sentiment_dag.fetch_stock_prices manual__2025-05-16T10:46:29.925523+00:00 [queued]>
[2025-05-16T10:46:33.347+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_stock_news_and_sentiment_dag.fetch_stock_prices manual__2025-05-16T10:46:29.925523+00:00 [queued]>
[2025-05-16T10:46:33.348+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-16T10:46:33.365+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_stock_prices> on 2025-05-16 10:46:29.925523+00:00
[2025-05-16T10:46:33.373+0000] {standard_task_runner.py:72} INFO - Started process 338 to run task
[2025-05-16T10:46:33.378+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_stock_news_and_sentiment_dag', 'fetch_stock_prices', 'manual__2025-05-16T10:46:29.925523+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/daily_news_sentiment_dag.py', '--cfg-path', '/tmp/tmpaj42oi9e']
[2025-05-16T10:46:33.380+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask fetch_stock_prices
[2025-05-16T10:46:33.446+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_stock_news_and_sentiment_dag.fetch_stock_prices manual__2025-05-16T10:46:29.925523+00:00 [running]> on host 9f5193fcdf75
[2025-05-16T10:46:33.546+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_stock_news_and_sentiment_dag' AIRFLOW_CTX_TASK_ID='fetch_stock_prices' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T10:46:29.925523+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-16T10:46:29.925523+00:00'
[2025-05-16T10:46:33.548+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-16T10:46:33.549+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-16T10:46:33.550+0000] {logging_mixin.py:190} INFO - Current task name:fetch_stock_prices state:running start_date:2025-05-16 10:46:33.337122+00:00
[2025-05-16T10:46:33.550+0000] {logging_mixin.py:190} INFO - Dag name:daily_stock_news_and_sentiment_dag and current dag run status:running
[2025-05-16T10:46:33.551+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-16T10:46:37.690+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/daily_news_sentiment_dag.py", line 72, in fetch_stock_prices
    engine = pg_hook.get_sqlalchemy_engine()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 253, in get_sqlalchemy_engine
    url = self.sqlalchemy_url
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/hooks/postgres.py", line 112, in sqlalchemy_url
    conn = self.connection
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 180, in connection
    self._connection = self.get_connection(self.get_conn_id())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-05-16T10:46:37.708+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-16T10:46:37.709+0000] {logging_mixin.py:190} INFO - Task start:2025-05-16 10:46:33.337122+00:00 end:2025-05-16 10:46:37.707529+00:00 duration:4.370407
[2025-05-16T10:46:37.710+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_stock_prices> dag:<DAG: daily_stock_news_and_sentiment_dag> dagrun:<DagRun daily_stock_news_and_sentiment_dag @ 2025-05-16 10:46:29.925523+00:00: manual__2025-05-16T10:46:29.925523+00:00, state:running, queued_at: 2025-05-16 10:46:29.974516+00:00. externally triggered: True>
[2025-05-16T10:46:37.711+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `postgres_default` isn't defined
[2025-05-16T10:46:37.712+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_stock_news_and_sentiment_dag, task_id=fetch_stock_prices, run_id=manual__2025-05-16T10:46:29.925523+00:00, execution_date=20250516T104629, start_date=20250516T104633, end_date=20250516T104637
[2025-05-16T10:46:37.756+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-16T10:46:37.759+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task fetch_stock_prices (The conn_id `postgres_default` isn't defined; 338)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/daily_news_sentiment_dag.py", line 72, in fetch_stock_prices
    engine = pg_hook.get_sqlalchemy_engine()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 253, in get_sqlalchemy_engine
    url = self.sqlalchemy_url
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/hooks/postgres.py", line 112, in sqlalchemy_url
    conn = self.connection
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 180, in connection
    self._connection = self.get_connection(self.get_conn_id())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-05-16T10:46:37.786+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-16T10:46:37.819+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-16T10:46:37.823+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
